spring.application.name=OrderManMicroService

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Security Credentials
spring.security.user.name=admin
spring.security.user.password=admin123

# Logging Level
//level.com.example.demo=INFO

# Force session expiration after 2 minutes of inactivity
spring.lifecycle.timeout-per-shutdown-phase=2m
server.servlet.session.timeout=2m